config/routes.rb
Blog::Application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #validations
  validates_presence_of :author
  validates_presence_of :body
  
  #associations
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  #validations 
  validates_presence_of :title
  validates_presence_of :body
  
  #associations
  has_many :comments, as: :commentable
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end
  
  http_basic_authenticate_with name: "katy", password: "nicholas", only: :destroy
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  http_basic_authenticate_with name: "katy", password: "nicholas", except: [:index, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    
    if post.update_attributes(post_params)
      flash[:info] = 'Post successfully updated!'
    else
      flash[:error] = 'fail town'
    end
    
    redirect_to post_path(post)
  end
  
  def create
    post = Post.new(post_params)
    
    if post.save
      flash[:info] = "Success!"
    else
      flash[:error] = "ERROR: #{post.errors.full_messages.to_sentence}"
    end
    
    redirect_to post_path(post)
  end
 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end
  
  private
  
  def post_params
    params.require(:post).permit(:body, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.haml
%h2 new comment

= form_for @comment, url: post_comments_path(@post) do |t|
  = t.text_field :author, placeholder: 'author'
  = t.text_area :body, placeholder: 'body'
  = t.submit 'Create Comment', class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if flash[:error] %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% elsif flash[:info] %>
    <div class="alert alert-success">
      <%= flash[:info] %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.haml
%h1 edit post

= form_for @post do |f|
  = f.text_field :title, place_holder: 'title'
  = f.text_area :body, place_holder: 'body'
  = f.submit 'Update', class: 'btn btn-primary'
  

app/views/posts/index.html.haml
%h1 Pedals and Pitons

.left-column
  .inner
    = image_tag 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Gunks_Traps_-_Pitons_on_Shockley%27s_Ceiling_-_2.jpg/90px-Gunks_Traps_-_Pitons_on_Shockley%27s_Ceiling_-_2.jpg', class: 'pull-left'
    
.right-column
  .inner
    - @posts.each do |post|
      .post.pull-left
        %h3= link_to post.title, post_path(post)
        %p= post.body
    
%hr.clearfix

= link_to "#{fa_icon('plus')} New Post".html_safe, new_post_path, class: 'btn btn-primary'

  
  

app/views/posts/new.html.haml
%h1 new post

= form_for @post do |f|
  = f.text_field :title, placeholder: 'title'
  = f.text_area :body, placeholder: 'body'
  = f.submit 'Create Post', class: 'btn btn-primary'

app/views/posts/show.html.haml
%h3= @post.title
%p= @post.body

%hr
%h4 Comments
- @post.comments.each do |comment|
  %h5 #{time_ago_in_word(comment_created_at)} ago
  %p= comment.body
  %hr

= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary'
= link_to 'Index', root_path, class: 'btn btn-default'
= link_to 'Comment', new_post_comment_path(@post), class: 'btn btn-default'